{%raw%}
name: GitHub Pages

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment
  pull_request:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      DTC_HEADLES: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
      - name: Download the Structurizr Cli
        run: curl --show-error --location https://github.com/structurizr/cli/releases/download/v1.26.0/structurizr-cli-1.26.0.zip  -o tmp.zip && unzip -d bin/structurizr-cli/. tmp.zip && rm tmp.zip
      - name: Generate C4 Diagrams
        run: ./bin/structurizr-cli/structurizr.sh export -w bank.dsl -format plantuml/structurizr -output documentation/diagrams
      - name: Migrate Markdown based ADRs from adr-tools to AsciiDoc
        run: gem install kramdown-asciidoc && for f in ./documentation/adrs/*.md; do kramdoc $f; done
      - name: Setup docToolchain
        run: chmod +x dtcw
      - name: Generate HTML site
        run: ./dtcw generateHTML
      - name: Copy documentation to public
        run: cp -r ./build/html5 ./public && mv ./public/internet-banking-system.html ./public/index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
{%endraw%}